wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("new", views.new, name="new"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("search", views.search, name="search"),
    path("randompage", views.randompage, name="randompage")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django import forms

from . import util
import markdown2
import random


class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    markdown = forms.CharField(label="Markdown", widget=forms.Textarea)


class EditEntryForm(forms.Form):
    markdown = forms.CharField(label="Markdown", widget=forms.Textarea)


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    entry = util.get_entry(title)
    if entry is None:
        return HttpResponse(f'The entry {title} does not exist.')
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": markdown2.markdown(entry)
        })


def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            markdown = bytes(form.cleaned_data["markdown"], 'utf-8')
            entry = util.get_entry(title)
            if entry is None:
                util.save_entry(title, markdown)
                return redirect(f'/wiki/{title}')
            else:
                return render(request, "encyclopedia/new.html", {
                    "form": form,
                    "error_msg": "An entry with the title already exists. Please write a different title."
                })
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form,
                "error_msg": "The form entry/entries are invalid. Please check again."
            })

    return render(request, "encyclopedia/new.html", {
        "form": NewEntryForm()
    })


def edit(request, title):
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            markdown = bytes(form.cleaned_data["markdown"], 'utf-8')
            util.save_entry(title, markdown)
            return redirect(f"/wiki/{title}")
        else:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "form": form,
                "error_msg": "The form entry/entries are invalid. Please check again."
            })

    entry = util.get_entry(title)
    if entry is None:
        return HttpResponse(f"The entry { title } does not exist.")
    form = EditEntryForm(initial={'markdown': entry})
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "form": form
    })


def search(request):
    if request.method == "POST":
        query = request.POST["q"]
        entry = util.get_entry(query)
        if entry is None:
            entries = util.list_entries()
            search_results = []
            for item in entries:
                if query.lower() in item.lower():
                    search_results.append(item)
            return render(request, "encyclopedia/search.html", {
                "query": query,
                "search_results": search_results
            })
        else:
            return render(request, "encyclopedia/entry.html", {
                "title": query.capitalize(),
                "entry": markdown2.markdown(entry)
            })


def randompage(request):
    randomentry = random.choice(util.list_entries())
    return redirect(f"/wiki/{randomentry}")

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %} {%block title%} Edit {{title}}
{%endblock%} {%block body%}
<h1>Edit page</h1>
{% if error_msg %}
<div class="alert alert-warning" role="alert">{{ error_msg }}</div>
{% endif %}
<form action="{% url 'encyclopedia:edit' title %}" method="POST">
	{{ form.as_p }} {% csrf_token %}
	<input type="submit" value="Save Changes" class="btn btn-success" />
</form>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %} {% block title %} {{title}}
{%endblock%} {%block body%} {{ entry|safe }}
<a href="{% url 'encyclopedia:edit' title%}" class="btn btn-dark">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia
{%endblock %} {% block body %}
<h1>ALL PAGES</h1>

<ul class="entry-list">
	{% for entry in entries %}
	<li>
		<a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
	</li>

	{% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
			crossorigin="anonymous"
		/>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;700&display=swap"
			rel="stylesheet"
		/>
		<link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
	</head>
	<body>
		<div class="wrapper">
			<div class="sidebar">
				<div><h2>Wiki</h2></div>
				<div>
					<form action="{% url 'encyclopedia:search' %}" method="POST">
						<div>
							<input
								class="search"
								type="text"
								name="q"
								placeholder="Search Encyclopedia"
							/>
						</div>
						{% csrf_token %}
					</form>
				</div>
				<div>
					<ul class="links-list">
						<li><a href="{% url 'encyclopedia:index' %}">Home</a></li>
						<li><a href="{% url 'encyclopedia:new' %}">Create New Page</a></li>
						<li>
							<a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
						</li>
					</ul>
				</div>
				{% block nav %} {% endblock %}
			</div>
			<div class="main">{% block body %} {% endblock %}</div>
		</div>
	</body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %} {%block title%} Create New Entry
{%endblock%} {%block body%}
<h1>Add Entry Details</h1>
{% if error_msg %}
<div class="alert alert-warning" role="alert">{{ error_msg }}</div>
{% endif %}
<form action="{% url 'encyclopedia:new' %}" method="POST">
	{{ form.as_p }} {% csrf_token %}
	<input type="submit" value="Create" class="btn btn-success" />
</form>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %} {%block title%} {{query}} - Search
Results {%endblock%} {%block body%}
<h1>'{{query}}' - Search Results</h1>
<ul>
	{% for result in search_results %}
	<li><a href="{% url 'encyclopedia:entry' result %}"> {{result}} </a></li>
	{% empty %}
	<p>No search results found for '{{query}}'</p>
	{% endfor %}
</ul>
{%endblock%}